config/routes.rb
Rails.application.routes.draw do
  get 'playgrounds/singleviewdesign'

  get 'playgrounds/mainviewdesign'

  get 'playgrounds/navbar'

  get 'playgrounds/playground'

  resources :wallpapers
  root to: "wallpapers#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/wallpaper.rb
class Wallpaper < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/playgrounds_controller.rb
class PlaygroundsController < ApplicationController
  def playground
  end
end

app/controllers/wallpapers_controller.rb
class WallpapersController < ApplicationController
  before_action :set_wallpaper, only: [:show, :edit, :update, :destroy]

  # GET /wallpapers
  # GET /wallpapers.json
  def index
    @wallpapers = Wallpaper.all
  end

  # GET /wallpapers/1
  # GET /wallpapers/1.json
  def show
  end

  # GET /wallpapers/new
  def new
    @wallpaper = Wallpaper.new
  end

  # GET /wallpapers/1/edit
  def edit
  end

  # POST /wallpapers
  # POST /wallpapers.json
  def create
    @wallpaper = Wallpaper.new(wallpaper_params)

    respond_to do |format|
      if @wallpaper.save
        format.html { redirect_to @wallpaper, notice: 'Wallpaper was successfully created.' }
        format.json { render :show, status: :created, location: @wallpaper }
      else
        format.html { render :new }
        format.json { render json: @wallpaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wallpapers/1
  # PATCH/PUT /wallpapers/1.json
  def update
    respond_to do |format|
      if @wallpaper.update(wallpaper_params)
        format.html { redirect_to @wallpaper, notice: 'Wallpaper was successfully updated.' }
        format.json { render :show, status: :ok, location: @wallpaper }
      else
        format.html { render :edit }
        format.json { render json: @wallpaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wallpapers/1
  # DELETE /wallpapers/1.json
  def destroy
    @wallpaper.destroy
    respond_to do |format|
      format.html { redirect_to wallpapers_url, notice: 'Wallpaper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wallpaper
      @wallpaper = Wallpaper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wallpaper_params
      params.fetch(:wallpaper, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playgrounds_helper.rb
module PlaygroundsHelper
end

app/helpers/wallpapers_helper.rb
module WallpapersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aristocrat</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="">
        <meta name="author" content="">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

        
        
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        
        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        
        <!-- Latest compiled JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        
        <!--jsPDF-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.min.js"></script>
        
        <!--DtataTables-->
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" type="text/css" />
        <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
        <script type="text/javascript" language="javascript" src="//cdn.datatables.net/buttons/1.4.2/js/buttons.print.min.js"></script>
        <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/dataTables.buttons.min.js"></script>
        <script src="https://cdn.datatables.net/responsive/2.1.0/js/dataTables.responsive.js"></script>
        <link href="//cdn.datatables.net/responsive/2.1.1/css/dataTables.responsive.css"/>
        
        <!--Font Awesome-->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css" />
        
        
  </head>

  <body>
  
    <header>
        <nav class="navbar navbar-default navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <%= link_to "Aristocrat", root_path, class: "navbar-brand" %>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                <li><%= link_to "Home", root_path  %></li>
                <li><%= link_to "About", root_path  %></li>
                <li><%= link_to "Contact", root_path  %></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <li>
                  <%= link_to new_wallpaper_path do %>
                  
                    <span class="glyphicon glyphicon-plus"></span>
                  
                  <% end %>
                  </li>
                <li class="dropdown">
                  <a href="#" class="glyphicon glyphicon-user dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    <li><a href="#"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                    <li><a href="#"><span class="glyphicon glyphicon-register"></span> Register</a></li>
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Nav header</li>
                    <li><a href="#">Separated link</a></li>
                    <li><a href="#">One more separated link</a></li>
                  </ul>
                </li>
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </nav>
    </header>

    
    <%= yield %>
  </body>
</html>

app/views/playgrounds/mainviewdesign.html.erb
    <!-- Page Content -->
    <div class="container">

        <!-- Page Header -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">IO Games
                    <small>A Collection of The Best io games</small>
                </h1>
            </div>
        </div>
        <!-- /.row -->

        <!-- Projects Row -->
        <div class="row">
            <div class="col-md-4 portfolio-item">
                <div class="shadow ">
                    <div class="well white">
                        <a href="#">
                            <img class="img-responsive" src="http://is2.mzstatic.com/image/thumb/Purple18/v4/60/f3/b5/60f3b5ca-7e1a-6231-f9e6-6dc5e1fdb880/source/520x293bb.jpg" width="700px" height="400px" alt="">
                        </a>
                        <h3>
                            <a href="#">Game Name</a>
                        </h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4 portfolio-item">
                <div class="shadow ">
                    <div class="well white">
                        <a href="#">
                            <img class="img-responsive" src="http://is3.mzstatic.com/image/thumb/Purple117/v4/5c/11/bd/5c11bd03-60c7-4c62-42cd-c2375fb24303/source/520x293bb.jpg" alt="">
                        </a>
                        <h3>
                            <a href="#">Game Name</a>
                        </h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4 portfolio-item">
                <div class="shadow ">
                    <div class="well white">
                        <a href="#">
                            <img class="img-responsive" src="http://is1.mzstatic.com/image/thumb/Purple128/v4/46/38/c6/4638c6a2-9582-3014-5c3a-019332194f57/source/520x293bb.jpg" alt="">
                        </a>
                        <h3>
                            <a href="#">Game Name</a>
                        </h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row -->

        <!-- Projects Row -->
        <div class="row">
            <div class="col-md-4 portfolio-item">
                <div class="shadow ">
                    <div class="well white">
                        <a href="#">
                            <img class="img-responsive" src="http://is3.mzstatic.com/image/thumb/Purple71/v4/a5/ca/b8/a5cab828-f29a-cc55-bba6-2601fbe3cf5c/source/520x293bb.jpg" alt="">
                        </a>
                        <h3>
                            <a href="#">Game Name</a>
                        </h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4 portfolio-item">
                <div class="shadow ">
                    <div class="well white">
                        <a href="#">
                            <img class="img-responsive" src="http://is5.mzstatic.com/image/thumb/Purple122/v4/d3/9a/19/d39a193c-9900-9653-dcd3-296a5a789373/source/520x293bb.jpg" alt="">
                        </a>
                        <h3>
                            <a href="#">Game Name</a>
                        </h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4 portfolio-item">
                <div class="shadow ">
                    <div class="well white">
                        <a href="#">
                            <img class="img-responsive" src="http://is2.mzstatic.com/image/thumb/Purple4/v4/f8/28/98/f8289810-d173-8ca2-be55-90a41da0f27e/source/520x293bb.jpg" alt="">
                        </a>
                        <h3>
                            <a href="#">Game Name</a>
                        </h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
                    </div>
                </div>
            </div>
        </div>

        <!-- Projects Row -->
        <div class="row">
            <div class="col-md-4 portfolio-item">
                <div class="shadow ">
                    <div class="well white">
                        <a href="#">
                            <img class="img-responsive" src="http://is3.mzstatic.com/image/thumb/Purple60/v4/7f/ca/13/7fca13d2-7ce7-afc9-a2c9-35d0588f40aa/source/520x293bb.jpg" alt="">
                        </a>
                        <h3>
                            <a href="#">Game Name</a>
                        </h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4 portfolio-item">
                <div class="shadow ">
                    <div class="well white">
                        <a href="#">
                            <img class="img-responsive" src="http://is5.mzstatic.com/image/thumb/Purple71/v4/0e/46/79/0e467921-2121-37c0-c84a-8fe25b76f0fd/source/520x293bb.jpg" alt="">
                        </a>
                        <h3>
                            <a href="#">Game Name</a>
                        </h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4 portfolio-item">
                <div class="shadow ">
                    <div class="well white">
                        <a href="#">
                            <img class="img-responsive" src="http://is2.mzstatic.com/image/thumb/Purple19/v4/59/5f/3a/595f3a00-2aa7-6896-ab02-1a287a82cd2d/source/520x293bb.jpg" alt="">
                        </a>
                        <h3>
                            <a href="#">Game Name</a>
                        </h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Pagination -->
        <div class="row text-center">
            <div class="col-lg-12">
                <ul class="pagination">
                    <li>
                        <a href="#">&laquo;</a>
                    </li>
                    <li class="active">
                        <a href="#">1</a>
                    </li>
                    <li>
                        <a href="#">2</a>
                    </li>
                    <li>
                        <a href="#">3</a>
                    </li>
                    <li>
                        <a href="#">4</a>
                    </li>
                    <li>
                        <a href="#">5</a>
                    </li>
                    <li>
                        <a href="#">&raquo;</a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- /.row -->

app/views/playgrounds/navbar.html.erb
<div class="container center">
    
    <h1>Testing Bootstrap Navbar</h1>
    <br></br><br></br>
    <br></br><br></br>
    
    <%= link_to new_wallpaper_path do %>
      <button type="button" class="btn btn-success" aria-label="Left Align">
        <span class="fa fa-plus fa-lg" aria-hidden="true"></span>
      </button>
    <% end %>
    &nbsp;&nbsp;
    <%= link_to new_wallpaper_path do %>
      <button type="button" class="btn btn-default" aria-label="Left Align">
        <span class="fa fa-user fa-lg" aria-hidden="true"></span>
      </button>
    <% end %>
    
                      <ul class="nav navbar-nav navbar-right">
                <li>
                  <%= link_to new_wallpaper_path do %>
                  <button class="btn btn-success" type="submit">
                    <span class="glyphicon glyphicon-plus"></span>
                  </button>
                  <% end %>
                  </li>
                <li class="dropdown">
                  <a href="#" class="btn btn-default navbar-btn glyphicon glyphicon-user dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    <li><a href="#"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                    <li><a href="#"><span class="glyphicon glyphicon-register"></span> Register</a></li>
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Nav header</li>
                    <li><a href="#">Separated link</a></li>
                    <li><a href="#">One more separated link</a></li>
                  </ul>
                </li>
              </ul>
    


</div>



<nav class="navbar navbar-inverse" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-3">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#"><i class="fa fa-home fa-fw"></i>Start</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-3">
    <ul class="nav navbar-nav">

        <li class="dropdown"> 
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-gift fa-fw"></i> Benefit</a>
       
         <ul class="dropdown-menu">
          <li><a href="#"> Hinzufuegen </a></li>
          <li><a href="#"> Benefitanbieter </a></li>
		   <li><a href="#"> Benefitpordukte n.LA </a></li>
          
         </ul>
        </li>
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-building-o fa-fw"></i> company</a>
        <ul class="dropdown-menu">
         <li><a href="#"> Anlegen </a></li>
          <li><a href="#">  Anlegen/Bearbeiten </a></li>
              </ul> 
           </li> 
      
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-tachometer fa-fw"></i> Home</a></li> 
    	
      		<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-users fa-fw"></i> Kunden</a></li> 
      
           <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-ticket fa-fw"></i> Modul Gesundheit</a>
           <ul class="dropdown-menu">
            <li><a href="#"><i class="fa fa-calendar fa-fw"></i> Buchungen </a></li>
              </ul> 
           </li> 
      
      
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>


<!--===================== custom nav ===========================-->

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/playgrounds/playground.html.erb
<div class="container center">
  <h1>,,PlayGround Area,,</h1>
</div>

app/views/playgrounds/singleviewdesign.html.erb
    <!-- Page Content -->
    <div class="container">

        <!-- Page Header -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">IO Games
                    <small>A Collection of The Best io games</small>
                </h1>
            </div>
        </div>
        <!-- /.row -->

        <!-- Projects Row -->
        <div class="row">
            <div class="col-md-8 col-md-offset-2 portfolio-item">
                <div class="shadow ">
                    <div class="well white">
                        
                        <a href="#">
                            <img class="img-responsive" src="http://is3.mzstatic.com/image/thumb/Purple117/v4/5c/11/bd/5c11bd03-60c7-4c62-42cd-c2375fb24303/source/520x293bb.jpg" width="700px" height="400px" alt="">
                        </a>
                        <h3 class="inline">
                            <a href="#">Game Name</a>
                        </h3>

                        <button class="btn btn-warning disabled game-btn1">Favorite</button> 
                        <button class="btn btn-success game-btn2">Like</button> 
                        <button class="btn btn-danger game-btn3">Dislike</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Pagination -->

app/views/wallpapers/_form.html.erb
<%= form_with(model: wallpaper, local: true) do |form| %>
  <% if wallpaper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wallpaper.errors.count, "error") %> prohibited this wallpaper from being saved:</h2>

      <ul>
      <% wallpaper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wallpapers/edit.html.erb
<h1>Editing Wallpaper</h1>

<%= render 'form', wallpaper: @wallpaper %>

<%= link_to 'Show', @wallpaper %> |
<%= link_to 'Back', wallpapers_path %>

app/views/wallpapers/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container center">
  <br>
  <div class="jumbotron">
    <h1>Wallpapers</h1>
    <br>
    <%= link_to 'New Wallpaper', new_wallpaper_path, class: 'btn btn-success' %>
    
    <%= link_to new_wallpaper_path do %>
      <button type="button" class="btn btn-success" aria-label="Left Align">
        <span class="fa fa-plus fa-lg" aria-hidden="true"></span>
      </button>
    <% end %>

      <a class="btn btn-danger" href="#">
      <i class="glyphicon glyphicon-align-left"></i> Delete</a>
    <%= button_tag type: 'submit', class: "button my-button", id: "register-button" do %>
        <i class="fa fa-lock" aria-hidden="true"></i>
    <% end %>
  </div>
    <br></br><br></br>
    <%= link_to playgrounds_mainviewdesign_path do %>
      <button type="button" class="btn btn-default">
        <i class="fa fa-lock fa-2x" aria-hidden="true"></i>
      </button>
    <% end %>
    &nbsp; &nbsp; &nbsp;
    <%= link_to playgrounds_singleviewdesign_path do %>
      <button type="button" class="btn btn-default">
        <i class="fa fa-lock fa-2x" aria-hidden="true"></i>
      </button>
    <% end %>
    &nbsp; &nbsp; &nbsp;
    <%= link_to playgrounds_navbar_path do %>
      <button type="button" class="btn btn-default">
        <i class="fa fa-lock fa-2x" aria-hidden="true"></i>
      </button>
    <% end %>
</div>


<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wallpapers.each do |wallpaper| %>
      <tr>
        <td><%= link_to 'Show', wallpaper %></td>
        <td><%= link_to 'Edit', edit_wallpaper_path(wallpaper) %></td>
        <td><%= link_to 'Destroy', wallpaper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/wallpapers/new.html.erb
<h1>New Wallpaper</h1>

<%= render 'form', wallpaper: @wallpaper %>

<%= link_to 'Back', wallpapers_path %>

app/views/wallpapers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_wallpaper_path(@wallpaper) %> |
<%= link_to 'Back', wallpapers_path %>